/**
 * Generates Tailwind v4 theme tokens from edit_content/theme/theme.yaml.
 *
 * Reads the YAML (single source of truth for brand colors + typography) and
 * emits src/theme.generated.css containing the `@theme` block that
 * src/index.css imports. Run before `vite dev` / `vite build` (wired in
 * package.json scripts).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { parse as parseYaml } from 'yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const themeYamlPath = path.join(rootDir, 'edit_content', 'theme', 'theme.yaml');
const outputPath = path.join(rootDir, 'src', 'theme.generated.css');

function fail(message) {
  console.error(`[generate-theme] ERROR: ${message}`);
  process.exit(1);
}

let themeConfig;
try {
  themeConfig = parseYaml(readFileSync(themeYamlPath, 'utf8'));
} catch (error) {
  fail(`could not read/parse ${themeYamlPath}: ${error.message}`);
}

const { brandColors } = themeConfig?.colors ?? {};
const { neutrals } = themeConfig?.colors ?? {};
const { textFont } = themeConfig?.typography ?? {};

if (!brandColors?.primary || !brandColors?.secondary) {
  fail('theme.yaml must define colors.brandColors.primary and colors.brandColors.secondary');
}
if (!neutrals?.darkNeutral || !neutrals?.lightNeutral || !neutrals?.secondaryNeutral) {
  fail('theme.yaml must define colors.neutrals.darkNeutral, lightNeutral and secondaryNeutral');
}
if (!textFont?.fontFamily || !textFont?.fontFallback) {
  fail('theme.yaml must define typography.textFont.fontFamily and fontFallback');
}

const css = `/* GENERATED FILE - do not edit. Generated by scripts/generate-theme.mjs from edit_content/theme/theme.yaml */
@theme {
  --color-tn-teal: ${brandColors.primary};
  --color-tn-brown: ${brandColors.secondary};
  --color-tn-black: ${neutrals.darkNeutral};
  --color-tn-white: ${neutrals.lightNeutral};
  --color-tn-gray: ${neutrals.secondaryNeutral};
  --color-tn-light: ${neutrals.lightNeutral};
  --color-tn-dark: ${neutrals.darkNeutral};
  --font-sans: '${textFont.fontFamily}', ${textFont.fontFallback};
}
`;

writeFileSync(outputPath, css, 'utf8');
console.log(`[generate-theme] Wrote ${path.relative(rootDir, outputPath)}`);